name: Deploy Backend Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" > .env
      
      - name: Login to docker hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build docker image
        run: docker build -t maxicrah/backen-grupo11 .
      
      - name: Publish image to docker hub
        run: docker push maxicrah/backen-grupo11:latest
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull maxicrah/backen-grupo11:latest
      
      - name: Delete old container
        run: docker rm -f backen-grupo11-container  
      - name: Run docker container
        run: docker run -d -p 4000:4000 --name backen-grupo11-container maxicrah/backen-grupo11:latest
